### ISSUE TITLE
Documentation missing.

### ISSUE THREAD

**Issue by kjetilge** [apendua/meteor-tags#1]
Even tough it's a small package I'm not able to figure out how to use this by just reading the code. A few lines of explanation would probably suffice.

**Comment by apendua** [comment]
@kjetilge You're totally right. I'll fix this as soon as possible.

**Comment by kjetilge** [comment]
I just couldn't stop trying to get "tags" work, and I think I'm on to something now.

I have put this in my code:
Tags.TagsMixin(MyCollection). that way some of the vars inside tags.js get some essential values :-)

and in view
{{#with MyCollection}}
        {{renderTags}}
        {{addTagButton}}
{{/with}}

but still I get "Cannot call method 'toLowerCase' of undefined " and 
403, reason: "Action not allowed"

 I'm logged in with Facebook.

Any hints for me ?
1. mai 2013 kl. 15:57 skrev Tomasz Lenarcik notifications@github.com:

**Comment by apendua** [comment]
@kjetilge You should start with:

``` javascript
MyCollection = new Meteor.Collection("myCollection");
Tags.TagsMixin(MyCollection);
```

so you're correct about this one. Now you can do stuff like:

``` javascript
MyCollection.addTag('tagName', selector);
MyCollection.removeTag('tagName', selector);
```

The reason, you're getting "Action not allowed" message is that another thing you need to do now is:

``` javascript
MyCollection.allowTags(function () {
    // clearly this is pretty unsafe
    return true;
});
```

Now, you're ready to go with your views. Supposing you have a helper:

``` javacript
Template.myTeplate.data = function () {
    return MyCollection.findOne({...});
}
```

you can render tags attached to your data like this:

``` html
{{#with data}}
   <ul class="...">
      {{renderTags}}
      <li>{{addTagsButton}}</li>
   </ul>
{{/with}}
```

Additionally, you have a read only access to a collection `Meteor.tags` that keeps record about all tags existing in your database (at this moment this is only the number of references).

Please note, that this package is still a work in progress. In particular it lacks a lot of very important features. For example the `{{renderTags}}` and `{{addTagsButton}}` heleprs will only work correct with the first collection equiped with `TagsMixin`, but I'll fix this soon.

**Comment by kjetilge** [comment]
Thanks! I'll try this.
I think "tags" will become a very useful package :-)
1. mai 2013 kl. 22:42 skrev Tomasz Lenarcik notifications@github.com:

**Comment by kjetilge** [comment]
I had to change doc.tags to doc.Tags to make it work:

```
  var nRefs = safe(userId, collection, selector, function (doc) {
    // first add tagName to tag's list of selected documents
    if (tagName in doc.Tags) // this tag is already there so don't update
      return false;
    collection.update({_id:doc._id}, {$addToSet:{tags:tagName}});
    return true;
  });//safe
```

Now I can add and delete tags :-)
1. mai 2013 kl. 22:42 skrev Tomasz Lenarcik notifications@github.com:

**Comment by apendua** [comment]
@kjetilge You say:

> I had to change doc.tags to doc.Tags to make it work

I'm affraid that this is not correct. To make the add/remove tags buttons work, you must render them within a context of a document that already has `tags` attribute. If 'doc.Tags' works means probabbly that 'doc' is the `window` object (since `Tags` is a global object defined by the package).

On the other hand, even if you have a document without `tags` attribute, I guess that the right behavior shoud be to create it without throwing an error. I consider it a bug. Please, change your `smart.json` file to point directly to the `github` reposioty, i.e.:

``` javascript
"packages": {
    "tags": {
        "git": "https://github.com/apendua/meteor-tags.git",
        "branch": "master"
    },
    [...]
}
```

I'll fix that as soon as I can.

**Comment by kjetilge** [comment]
You where right about the error. Earlier, when I started to become delusional in my conquest, I added Tags: [] to the item creation code. Now I changed it to "tags" in both places and it all works! Thanks again.
1. mai 2013 kl. 00:27 skrev Tomasz Lenarcik notifications@github.com:

**Comment by apendua** [comment]
@kjetilge I already fixed it. If you update to the code from master branch everything should work fine.
