### ISSUE TITLE
listOfTags always empty

### ISSUE THREAD

**Issue by ninajlu** [apendua/meteor-tags#12]
I'm not sure what I am doing wrong but typeahead isn't working for me in autocompleting the tags. I tried logging the listOfTags in the newTagDialog.rendered function but kept getting an empty set. Any idea why this could be?

**Comment by ninajlu** [comment]
Actually typeahead doesn't even work if you add in a static source like
$(blah).typeahead({
    name: 'Some name',
    local: ['test', 'abc', 'def']
});
Have you gotten typeahead to work before with meteor or have any idea why nothing turns up at all?
(all I am able to get is the input textfield and no dropdown list of suggestions/typeahead)

**Comment by apendua** [comment]
@ninajlu This is interesting. Acctually I have never had any problems with `typeahead` feature. Do you think this may be connected somehow to the version of **bootstrap** that you are using? Are you using **bootstrap 2**? Are you sure that the `tags` collection is not empty?

**Comment by apendua** [comment]
@ninajlu I have an Idea what may be wrong. Have you published your tags? Basically you need to do this

``` javascript
// server side
Meteor.publish('tags', function () {
  return Meteor.tags.find({});
});

// client side
Meteor.subscribe('tags');
```

For some reason I decided not to do it automatically, which I think may be wrong strategy. I will think how to solve this seamlessly. By that time, please check if this is the reason why you are getting the empty `typeahead` list.

**Comment by ninajlu** [comment]
Thank you so much! I didn't think of that but you're right, I completely forgot to publish and subscribe to the tags.
After correcting that, all typeahead works! 
I was stuck on this problem for multiple hours yesterday so I just wanted to thank you again for your help.

**Comment by apendua** [comment]
@ninajlu You're welcome. It is my fault anyways, because I should have mentioned it in the `README` file.
