### ISSUE TITLE
ReferenceError: _ is not defined in 0.6.5

### ISSUE THREAD

**Issue by kjetilge** [apendua/meteor-tags#7]
In 0.6.5 i get ReferenceError: _ is not defined in 0.6.5.
I've tried to change Package.on_use section:
    api.use('underscore', ['client', 'server']); 
    api.use(['bootstrap', 'templating', 'jquery'], 'client');

The initial problem goes away but instead when I add:
Videoer = new Meteor.Collection('videoer');
Tags.TagsMixin(Videoer);

I get:
ReferenceError: Tags is not defined

Is it a bug or am I doing something wrong ?

**Comment by apendua** [comment]
@kjetilge The problem is that in Meteor 0.6.5 global objects defined by package need to be exported:

``` javascript
api.export('Tags')
```

It was already updated in the repository, but I forgot to publish the new tag on the atmosphere, so you were probably using out-of-date version. Now it's fixed and should work fine.
